kind: Deployment
apiVersion: apps/v1
metadata:
  name: eureka-test-v1
  namespace: test
  labels:
    app: eureka-test
    version: v1
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubesphere.io/creator: zhouy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-test
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: eureka-test
        version: v1
      annotations:
        cni.projectcalico.org/ipv4pools: '["default-ipv4-ippool"]'
        kubesphere.io/creator: zhouy
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
      containers:
        - name: container-eereki
          image: >-
            registry.cn-hangzhou.aliyuncs.com/yukikyu-namespace/eureka:SNAPSHOT-$BUILD_NUMBER
          ports:
            - name: http-0
              containerPort: 8761
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      imagePullSecrets:
        - name: ali-docker-register
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
